# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=code-server

before_install:
  - docker pull alpine
  - docker pull debian:buster-slim
  - docker pull php:fpm-buster

script:
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY" tag-latest
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":browse tag-browse
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":go tag-go
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":wp tag-wp
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":sage tag-sage
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":openlitespeed tag-openlitespeed
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":openlitespeed-sage tag-openlitespeed-sage
  - docker run -dit --name="$DEMYX_REPOSITORY" demyx/"$DEMYX_REPOSITORY"
  - docker exec "$DEMYX_REPOSITORY" code-server --version
  #- docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":alpine tag-alpine
  #- docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":wp-alpine tag-wp-alpine
  #- docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":sage-alpine tag-sage-alpine

after_success:
  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
  - docker push demyx/"$DEMYX_REPOSITORY"
  - docker push demyx/"$DEMYX_REPOSITORY":browse
  - docker push demyx/"$DEMYX_REPOSITORY":go
  - docker push demyx/"$DEMYX_REPOSITORY":wp
  - docker push demyx/"$DEMYX_REPOSITORY":sage
  - docker push demyx/"$DEMYX_REPOSITORY":openlitespeed
  - docker push demyx/"$DEMYX_REPOSITORY":openlitespeed-sage
  #- docker push demyx/"$DEMYX_REPOSITORY":alpine
  #- docker push demyx/"$DEMYX_REPOSITORY":wp-alpine
  #- docker push demyx/"$DEMYX_REPOSITORY":sage-alpine
  - bash travis.sh
